const AliasMap = require('../../aliasmap/lib/aliasmap');

const namedColors = new AliasMap();

namedColors.set('aliceblue', '#f0f8ff');
namedColors.set('antiquewhite', '#faebd7');
namedColors.set('cyan', '#00ffff', 'aqua');
namedColors.set('aquamarine', '#7fffd4');
namedColors.set('azure', '#f0ffff');
namedColors.set('beige', '#f5f5dc');
namedColors.set('bisque', '#ffe4c4');
namedColors.set('black', '#000000');
namedColors.set('blanchedalmond', '#ffebcd');
namedColors.set('blue', '#0000ff');
namedColors.set('blueviolet', '#8a2be2');
namedColors.set('brown', '#a52a2a');
namedColors.set('burlywood', '#deb887');
namedColors.set('cadetblue', '#5f9ea0');
namedColors.set('chartreuse', '#7fff00');
namedColors.set('chocolate', '#d2691e');
namedColors.set('coral', '#ff7f50');
namedColors.set('cornflowerblue', '#6495ed');
namedColors.set('cornsilk', '#fff8dc');
namedColors.set('crimson', '#dc143c');
namedColors.set('darkblue', '#00008b');
namedColors.set('darkcyan', '#008b8b');
namedColors.set('darkgoldenrod', '#b8860b');
namedColors.set('darkgray', '#a9a9a9', 'darkgrey');
namedColors.set('darkgreen', '#006400');
namedColors.set('darkkhaki', '#bdb76b');
namedColors.set('darkmagenta', '#8b008b');
namedColors.set('darkolivegreen', '#556b2f');
namedColors.set('darkorange', '#ff8c00');
namedColors.set('darkorchid', '#9932cc');
namedColors.set('darkred', '#8b0000');
namedColors.set('darksalmon', '#e9967a');
namedColors.set('darkseagreen', '#8fbc8f');
namedColors.set('darkslateblue', '#483d8b');
namedColors.set('darkslategray', '#2f4f4f', 'darkslategrey');
namedColors.set('darkturquoise', '#00ced1');
namedColors.set('darkviolet', '#9400d3');
namedColors.set('deeppink', '#ff1493');
namedColors.set('deepskyblue', '#00bfff');
namedColors.set('dimgray', '#696969', 'dimgrey');
namedColors.set('dodgerblue', '#1e90ff');
namedColors.set('firebrick', '#b22222');
namedColors.set('floralwhite', '#fffaf0');
namedColors.set('forestgreen', '#228b22');
namedColors.set('gainsboro', '#dcdcdc');
namedColors.set('ghostwhite', '#f8f8ff');
namedColors.set('gold', '#ffd700');
namedColors.set('goldenrod', '#daa520');
namedColors.set('gray', '#808080', 'grey');
namedColors.set('green', '#008000');
namedColors.set('greenyellow', '#adff2f');
namedColors.set('honeydew', '#f0fff0');
namedColors.set('hotpink', '#ff69b4');
namedColors.set('indianred', '#cd5c5c');
namedColors.set('indigo', '#4b0082');
namedColors.set('ivory', '#fffff0');
namedColors.set('khaki', '#f0e68c');
namedColors.set('lavender', '#e6e6fa');
namedColors.set('lavenderblush', '#fff0f5');
namedColors.set('lawngreen', '#7cfc00');
namedColors.set('lemonchiffon', '#fffacd');
namedColors.set('lightblue', '#add8e6');
namedColors.set('lightcoral', '#f08080');
namedColors.set('lightcyan', '#e0ffff');
namedColors.set('lightgoldenrodyellow', '#fafad2');
namedColors.set('lightgray', '#d3d3d3', 'lightgrey');
namedColors.set('lightgreen', '#90ee90');
namedColors.set('lightpink', '#ffb6c1');
namedColors.set('lightsalmon', '#ffa07a');
namedColors.set('lightseagreen', '#20b2aa');
namedColors.set('lightskyblue', '#87cefa');
namedColors.set('lightslategray', '#778899', 'lightslategrey');
namedColors.set('lightsteelblue', '#b0c4de');
namedColors.set('lightyellow', '#ffffe0');
namedColors.set('lime', '#00ff00');
namedColors.set('limegreen', '#32cd32');
namedColors.set('linen', '#faf0e6');
namedColors.set('magenta', '#ff00ff', 'fuchsia');
namedColors.set('maroon', '#800000');
namedColors.set('mediumaquamarine', '#66cdaa');
namedColors.set('mediumblue', '#0000cd');
namedColors.set('mediumorchid', '#ba55d3');
namedColors.set('mediumpurple', '#9370db');
namedColors.set('mediumseagreen', '#3cb371');
namedColors.set('mediumslateblue', '#7b68ee');
namedColors.set('mediumspringgreen', '#00fa9a');
namedColors.set('mediumturquoise', '#48d1cc');
namedColors.set('mediumvioletred', '#c71585');
namedColors.set('midnightblue', '#191970');
namedColors.set('mintcream', '#f5fffa');
namedColors.set('mistyrose', '#ffe4e1');
namedColors.set('moccasin', '#ffe4b5');
namedColors.set('navajowhite', '#ffdead');
namedColors.set('navy', '#000080');
namedColors.set('oldlace', '#fdf5e6');
namedColors.set('olive', '#808000');
namedColors.set('olivedrab', '#6b8e23');
namedColors.set('orange', '#ffa500');
namedColors.set('orangered', '#ff4500');
namedColors.set('orchid', '#da70d6');
namedColors.set('palegoldenrod', '#eee8aa');
namedColors.set('palegreen', '#98fb98');
namedColors.set('paleturquoise', '#afeeee');
namedColors.set('palevioletred', '#db7093');
namedColors.set('papayawhip', '#ffefd5');
namedColors.set('peachpuff', '#ffdab9');
namedColors.set('peru', '#cd853f');
namedColors.set('pink', '#ffc0cb');
namedColors.set('plum', '#dda0dd');
namedColors.set('powderblue', '#b0e0e6');
namedColors.set('purple', '#800080');
namedColors.set('rebeccapurple', '#663399');
namedColors.set('red', '#ff0000');
namedColors.set('rosybrown', '#bc8f8f');
namedColors.set('royalblue', '#4169e1');
namedColors.set('saddlebrown', '#8b4513');
namedColors.set('salmon', '#fa8072');
namedColors.set('sandybrown', '#f4a460');
namedColors.set('seagreen', '#2e8b57');
namedColors.set('seashell', '#fff5ee');
namedColors.set('sienna', '#a0522d');
namedColors.set('silver', '#c0c0c0');
namedColors.set('skyblue', '#87ceeb');
namedColors.set('slateblue', '#6a5acd');
namedColors.set('slategray', '#708090', 'slategrey');
namedColors.set('snow', '#fffafa');
namedColors.set('springgreen', '#00ff7f');
namedColors.set('steelblue', '#4682b4');
namedColors.set('tan', '#d2b48c');
namedColors.set('teal', '#008080');
namedColors.set('thistle', '#d8bfd8');
namedColors.set('tomato', '#ff6347');
namedColors.set('turquoise', '#40e0d0');
namedColors.set('violet', '#ee82ee');
namedColors.set('wheat', '#f5deb3');
namedColors.set('white', '#ffffff');
namedColors.set('whitesmoke', '#f5f5f5');
namedColors.set('yellow', '#ffff00');
namedColors.set('yellowgreen', '#9acd32');

module.exports = namedColors;
